name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Unit test
      run: pnpm run test
    - name: Build IWA example
      run: pnpm run build:iwa
      env: 
        KEY: ${{ secrets.IWA_KEY }}
        KEY_PASSPHRASE: ${{ secrets.IWA_KEY_PASSPHRASE }}
    - name: Build Chrome App example
      run: pnpm run build:chrome-app
    
