# Copyright 2025 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#        https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release Connector and Apps

on:
  push:
    tags:
      - 'connector-*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build Connector
        run: pnpm --filter sso-offloading-connector run build

      # - name: Publish Connector to NPM
      #   run: pnpm --filter sso-offloading-connector publish --no-git-checks
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Get all tags (for IWA manifest)
        uses: octokit/request-action@v2.x
        id: get_all_tags
        with:
          route: GET /repos/${{ github.repository }}/git/matching-refs/tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump IWA version and create iwa-update-manifest.json
        run: pnpm run bump:iwa
        env:
          TAG: ${{ github.ref_name }}
          ALL_TAGS_JSON: ${{ steps.get_all_tags.outputs.data }}

      - name: Build IWA example
        id: build_iwa_example
        run: pnpm run build:iwa
        env:
          KEY: ${{ secrets.IWA_KEY }}
          KEY_PASSPHRASE: ${{ secrets.IWA_KEY_PASSPHRASE }}

      - name: Bump Chrome App version
        run: pnpm run bump:chrome-app
        env:
          VERSION: ${{ env.VERSION }}

      - name: Build Chrome App example
        run: pnpm run build:chrome-app

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Package Chrome App
        id: package_chrome_app
        uses: ./.github/actions/pack-crx
        with:
          key: ${{ secrets.CHROME_APP_KEY }}
          input-dir: examples/chrome-app-example/chrome-app
          name: chrome-app

      - name: Generate Chrome App update_manifest.xml
        id: generate_app_manifest
        uses: ./.github/actions/generate-update-manifest-xml
        with:
          app-id: ${{ steps.package_chrome_app.outputs.crx-id }}
          app-version: ${{ env.VERSION }}
          crx-filename: 'chrome-app.crx'
          repository: ${{ github.repository }}
          github-tag: ${{ github.ref_name }}

      - name: Write Chrome App update_manifest.xml
        run: echo "${{ steps.generate_app_manifest.outputs.xml-content }}" > chrome_app_update_manifest.xml

      - name: Create GitHub Release for Connector
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: |
            examples/simple-iwa-example/dist/simple-iwa-example.swbn
            ${{ steps.package_chrome_app.outputs.crx-name }}
            ./iwa-update-manifest.json
            ./chrome_app_update_manifest.xml